package jboss.as.bond.market.model;

// Generated Mar 12, 2014 4:18:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AssetOption generated by hbm2java
 */
@Entity
@Table(name = "AssetOption", catalog = "BondMarket")
public class AssetOption implements java.io.Serializable {

	private int id;
	private Company company;
	private Float strike;
	private Date settlement;

	public AssetOption() {
	}

	public AssetOption(int id) {
		this.id = id;
	}

	public AssetOption(int id, Company company, Float strike, Date settlement) {
		this.id = id;
		this.company = company;
		this.strike = strike;
		this.settlement = settlement;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "strike", precision = 12, scale = 0)
	public Float getStrike() {
		return this.strike;
	}

	public void setStrike(Float strike) {
		this.strike = strike;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "settlement", length = 10)
	public Date getSettlement() {
		return this.settlement;
	}

	public void setSettlement(Date settlement) {
		this.settlement = settlement;
	}

}
