package jboss.as.bond.market.model;
// default package
// Generated Mar 13, 2014 4:27:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Auction generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Auction", catalog = "BondMarket")
public class Auction extends Trad  {

	
	private float auctionPrice;

	public Auction() {
	}

	

	@Column(name = "auction_price", precision = 12, scale = 0)
	public float getAuctionPrice() {
		return this.auctionPrice;
	}

	public void setAuctionPrice(float auctionPrice) {
		this.auctionPrice = auctionPrice;
	}

}
