package jboss.as.bond.market.model;
// default package
// Generated Mar 13, 2014 4:27:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Investisor generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Investisor", catalog = "BondMarket")
public class Investisor extends User{

	
	private Profile profile;
	private Set<Portfolio> portfolios = new HashSet<Portfolio>(0);

	public Investisor() {
	}
	

	public Investisor( Profile profile, Date createdAt, String email,
			Boolean isActive, String username, String password) {
		
	}

	@OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL )
	@JoinColumn(name = "profile")
	public Profile getProfile() {
		return this.profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "investisor")
	public Set<Portfolio> getPortfolios() {
		return this.portfolios;
	}

	public void setPortfolios(Set<Portfolio> portfolios) {
		this.portfolios = portfolios;
	}

	

}
