package jboss.as.bond.market.model;

// Generated Mar 12, 2014 4:18:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Investisor generated by hbm2java
 */
@Entity
@Table(name = "Investisor", catalog = "BondMarket")
public class Investisor implements java.io.Serializable {

	private int id;
	private Role role;
	private Profile profile;
	private Date createdAt;
	private String email;
	private Boolean isActive;
	private String name;
	private String username;
	private Set<Transaction> transactionsForBuyer = new HashSet<Transaction>(0);
	private Set<Portfolio> portfolios = new HashSet<Portfolio>(0);
	private Set<Auction> auctionsForBuyer = new HashSet<Auction>(0);
	private Set<Auction> auctionsForOwner = new HashSet<Auction>(0);
	private Set<Transaction> transactionsForOwner = new HashSet<Transaction>(0);

	public Investisor() {
	}

	public Investisor(int id) {
		this.id = id;
	}

	public Investisor(int id, Role role, Profile profile, Date createdAt,
			String email, Boolean isActive, String name, String username,
			Set<Transaction> transactionsForBuyer, Set<Portfolio> portfolios,
			Set<Auction> auctionsForBuyer, Set<Auction> auctionsForOwner,
			Set<Transaction> transactionsForOwner) {
		this.id = id;
		this.role = role;
		this.profile = profile;
		this.createdAt = createdAt;
		this.email = email;
		this.isActive = isActive;
		this.name = name;
		this.username = username;
		this.transactionsForBuyer = transactionsForBuyer;
		this.portfolios = portfolios;
		this.auctionsForBuyer = auctionsForBuyer;
		this.auctionsForOwner = auctionsForOwner;
		this.transactionsForOwner = transactionsForOwner;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profile")
	public Profile getProfile() {
		return this.profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdAt", length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "isActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "investisorByBuyer")
	public Set<Transaction> getTransactionsForBuyer() {
		return this.transactionsForBuyer;
	}

	public void setTransactionsForBuyer(Set<Transaction> transactionsForBuyer) {
		this.transactionsForBuyer = transactionsForBuyer;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "investisor")
	public Set<Portfolio> getPortfolios() {
		return this.portfolios;
	}

	public void setPortfolios(Set<Portfolio> portfolios) {
		this.portfolios = portfolios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "investisorByBuyer")
	public Set<Auction> getAuctionsForBuyer() {
		return this.auctionsForBuyer;
	}

	public void setAuctionsForBuyer(Set<Auction> auctionsForBuyer) {
		this.auctionsForBuyer = auctionsForBuyer;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "investisorByOwner")
	public Set<Auction> getAuctionsForOwner() {
		return this.auctionsForOwner;
	}

	public void setAuctionsForOwner(Set<Auction> auctionsForOwner) {
		this.auctionsForOwner = auctionsForOwner;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "investisorByOwner")
	public Set<Transaction> getTransactionsForOwner() {
		return this.transactionsForOwner;
	}

	public void setTransactionsForOwner(Set<Transaction> transactionsForOwner) {
		this.transactionsForOwner = transactionsForOwner;
	}

}
