package jboss.as.bond.market.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Portfolio generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Portfolio", catalog = "BondMarket")
public class Portfolio implements java.io.Serializable {

	private int id;
	private Investisor investisor;
	private String title;
	

	private Set<PortfolioLine> pfLines = new HashSet<PortfolioLine>(0);

	public Portfolio() {
	}
	
	public Portfolio(Investisor investisor, String title,
			Set<PortfolioLine> pfLines) {
		this.investisor = investisor;
		this.title = title;
		this.pfLines = pfLines;
	}

	public Portfolio(Investisor byId, String title2) {
		this.investisor = byId;
		this.title = title2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner")
	public Investisor getInvestisor() {
		return this.investisor;
	}

	public void setInvestisor(Investisor investisor) {
		this.investisor = investisor;
	}
	
	@OneToMany(mappedBy="pf")
	public Set<PortfolioLine> getPfLines() {
		return pfLines;
	}

	public void setPfLines(Set<PortfolioLine> pfLines) {
		this.pfLines = pfLines;
	}
	@Column(name="title")
	public String getTitle() {
		return title;
	}
	
	public void setTitle(String title) {
		this.title = title;
	}
	
	public void addPFLine(PortfolioLine pfl){
		this.getPfLines().add(pfl);
	}
}
