package jboss.as.bond.market.model;
// default package
// Generated Mar 13, 2014 4:27:29 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Profile generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Profile", catalog = "BondMarket")
public class Profile implements java.io.Serializable {

	private Integer id;
	private String firstname;
	private String lastname;
	private String phone;
	private Investisor investisor;
	
	public Profile() {
	}

	public Profile(String firstname, String lastname, String phone,
			Investisor investisor) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.phone = phone;
		this.investisor = investisor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "firstname")
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname")
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "profile")
	public Investisor getInvestisors() {
		return this.investisor;
	}

	public void setInvestisors(Investisor investisor) {
		this.investisor = investisor;
	}

}
