package jboss.as.bond.market.model;

// Generated Mar 12, 2014 4:18:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "Profile", catalog = "BondMarket")
public class Profile implements java.io.Serializable {

	private Integer id;
	private String firstname;
	private String lastname;
	private String phone;
	private Set<Investisor> investisors = new HashSet<Investisor>(0);

	public Profile() {
	}

	public Profile(String firstname, String lastname, String phone,
			Set<Investisor> investisors) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.phone = phone;
		this.investisors = investisors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "firstname")
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname")
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profile")
	public Set<Investisor> getInvestisors() {
		return this.investisors;
	}

	public void setInvestisors(Set<Investisor> investisors) {
		this.investisors = investisors;
	}

}
