package jboss.as.bond.market.model;
// default package
// Generated Mar 13, 2014 4:27:29 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Profile generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Profile", catalog = "BondMarket")
public class Profile implements java.io.Serializable {

	private Integer id;
	private String firstname;
	private String lastname;
	private Investisor investisor;
	private String  termTrading;
	private String market_capitalization;
	private String derivatives;
	
	public Profile() {
	}
	
	public Profile(String firstname, String lastname, String termTrading,
			String market_capitalization, String derivatives) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.termTrading = termTrading;
		this.market_capitalization = market_capitalization;
		this.derivatives = derivatives;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "firstname")
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname")
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "term_trading")
	public String getTermTrading() {
		return this.termTrading;
	}

	public void setTermTrading(String term_trading) {
		this.termTrading = term_trading;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "profile")
	public Investisor getInvestisors() {
		return this.investisor;
	}

	public void setInvestisors(Investisor investisor) {
		this.investisor = investisor;
	}
	@Column(name="capitalization")
	public String getMarket_capitalization() {
		return market_capitalization;
	}
		
	public void setMarket_capitalization(String market_capitalization) {
		this.market_capitalization = market_capitalization;
	}
	@Column(name="derivatives")
	public String getDerivatives() {
		return derivatives;
	}

	public void setDerivatives(String derivatives) {
		this.derivatives = derivatives;
	}
	

}
