package jboss.as.bond.market.model;
// default package
// Generated Mar 13, 2014 4:27:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Role", catalog = "BondMarket")
public class Role implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Member> members = new HashSet<Member>(0);
	private Set<Administrator> administrators = new HashSet<Administrator>(0);
	private Set<Investisor> investisors = new HashSet<Investisor>(0);

	public Role() {
	}

	public Role(String name, Set<Member> members,
			Set<Administrator> administrators, Set<Investisor> investisors) {
		this.name = name;
		this.members = members;
		this.administrators = administrators;
		this.investisors = investisors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Member> getMembers() {
		return this.members;
	}

	public void setMembers(Set<Member> members) {
		this.members = members;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Administrator> getAdministrators() {
		return this.administrators;
	}

	public void setAdministrators(Set<Administrator> administrators) {
		this.administrators = administrators;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Investisor> getInvestisors() {
		return this.investisors;
	}

	public void setInvestisors(Set<Investisor> investisors) {
		this.investisors = investisors;
	}

}
