package jboss.as.bond.market.model;
// default package
// Generated Mar 13, 2014 4:27:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * StockOption generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "StockOption", catalog = "BondMarket")
public class StockOption extends Asset{
	
	private float cote;

	public StockOption() {
	}


	@Column(name = "cote", precision = 12, scale = 0)
	public float getCote() {
		return this.cote;
	}

	public void setCote(float cote) {
		this.cote = cote;
	}

}
