package jboss.as.bond.market.model;
// default package
// Generated Mar 13, 2014 4:27:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Transaction generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Transaction", catalog = "BondMarket")
public class Transaction extends Trad  {


	public Transaction() {
	}

	

}
