package jboss.as.bond.market.model;

// Generated Mar 12, 2014 4:18:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "Transaction", catalog = "BondMarket")
public class Transaction implements java.io.Serializable {

	private int id;
	private Investisor investisorByOwner;
	private Investisor investisorByBuyer;
	private Date calledAt;
	private Float price;
	private Date puttedAt;
	private Integer quantity;
	private Integer asset;

	public Transaction() {
	}

	public Transaction(int id) {
		this.id = id;
	}

	public Transaction(int id, Investisor investisorByOwner,
			Investisor investisorByBuyer, Date calledAt, Float price,
			Date puttedAt, Integer quantity, Integer asset) {
		this.id = id;
		this.investisorByOwner = investisorByOwner;
		this.investisorByBuyer = investisorByBuyer;
		this.calledAt = calledAt;
		this.price = price;
		this.puttedAt = puttedAt;
		this.quantity = quantity;
		this.asset = asset;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner")
	public Investisor getInvestisorByOwner() {
		return this.investisorByOwner;
	}

	public void setInvestisorByOwner(Investisor investisorByOwner) {
		this.investisorByOwner = investisorByOwner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "buyer")
	public Investisor getInvestisorByBuyer() {
		return this.investisorByBuyer;
	}

	public void setInvestisorByBuyer(Investisor investisorByBuyer) {
		this.investisorByBuyer = investisorByBuyer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "calledAt", length = 10)
	public Date getCalledAt() {
		return this.calledAt;
	}

	public void setCalledAt(Date calledAt) {
		this.calledAt = calledAt;
	}

	@Column(name = "price", precision = 12, scale = 0)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "puttedAt", length = 10)
	public Date getPuttedAt() {
		return this.puttedAt;
	}

	public void setPuttedAt(Date puttedAt) {
		this.puttedAt = puttedAt;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "asset")
	public Integer getAsset() {
		return this.asset;
	}

	public void setAsset(Integer asset) {
		this.asset = asset;
	}

}
